### ISSUE TITLE
Missing file floatformat.js

### ISSUE THREAD

**Issue by jefftriplett** [chrisdickinson/plate#1]
Looks like a file didn't quite get checked in yet.

$ bin/build-plate 

Error: ENOENT, No such file or directory 'lib/filters/floatformat.js'

**Comment by chrisdickinson** [comment]
Whoooops. Sorry about that. Should be fixed now.

**Comment by chrisdickinson** [comment]
This is a placeholder comment retrieval.

**Comment by chrisdickinson** [comment]
Retrieving comments

**Comment by chrisdickinson** [comment]
(haha, sorry if you got some emails jeff! just testing a tool and it confused "get the comments" for "leave a comment" 😅)
